### ISSUE TITLE
Cannot import module

### ISSUE THREAD

**Issue by nunezmarco** [cwi-swat/clair#12]
Hi,

I'm trying to use ClaiR but am unable to import the module.
When doing import lang::cpp::AST;
I get the following error :
Could not import module lang::cpp::AST: can not find in search path
Even if the clair module is installed, it seems that the language is not in the path.

I soft linked the rascalmpl/eclipse/library/lang/cpp to src/lang/cpp folder and now run into an other error :
Cannot link method lang.cpp.internal.Parser because: class not found

. windows10
. eclipse 2019-06
. rascal 0.17.0 (stable)

**Comment by nunezmarco** [comment]
Yes, I did copy-paste of another issue, because the same thing happens to me and I did the exact same thing:(

**Comment by jurgenvinju** [comment]
We're having similar issues here. Will try to fix next week! Thanks for the report.

**Comment by rodinaarssen** [comment]
Hi nunezmarco. A new stable version of Rascal has been released this week (0.18.0). If you run ClaiR against this version of Rascal, do you still run into this error?

**Comment by rodinaarssen** [comment]
Closing this issue for now. Please get in touch again if you still have issues.
