### ISSUE TITLE
M3.macroDefinitions problems

### ISSUE THREAD

**Issue by jmerle** [cwi-swat/clair#15]
I just updated all my Eclipse plugins and noticed some errors in code that uses `M3.macroDefinitions`. It seems that the changes in https://github.com/cwi-swat/clair/commit/730b96dab0a7c752738f01248ca7fb34ac88dab2 created some bugs:
- `M3.macroDefinitions` now contains macro expansions instead of definitions (presumably caused by the change of `Stream.of(tu.getMacroDefinitions())` to `Stream.of(tu.getMacroExpansions())`).
- `M3.macroDefinitions` now contains a `rel[loc src, loc macro]` instead of the `rel[loc macro, loc src]` it used to be, even though the M3.rsc file still says it should be a `rel[loc macro, loc src]`.

**Comment by jmerle** [comment]
Here's a small example:

```rsc
module MacroDefinitions

import IO;
import lang::cpp::M3;

void main() {
	tempFile = |tmp:///definitions.c|;
	
	writeFile(tempFile, "#define SOME_CONSTANT 42
						'
						'int main() {
						'    int value = SOME_CONSTANT;
						'    return 0;
						'}");
	
	model = createM3FromCppFile(tempFile);
	
	println("model.macroDefinitions:");
	iprintln(model.macroDefinitions);
	
	println("model.macroExpansions:");
	iprintln(model.macroExpansions);
}
```

Outputs:

```
model.macroDefinitions:
{<|tmp:///definitions.c|(58,13),|cpp+macro:///SOME_CONSTANT|>}
model.macroExpansions:
{<|tmp:///definitions.c|(58,13),|cpp+macro:///SOME_CONSTANT|>}
```

Before the commit I linked `model.macroDefinitions` would contain `{<|cpp+macro:///SOME_CONSTANT|,|tmp:///definitions.c|(0,24)>}`, where the second location's offset and length are set to enclose `#define SOME_CONSTANT 42`.

**Comment by rodinaarssen** [comment]
Hi Jmerle. Thanks for the detailed report! I seem to have been a bit over-eager in copying. Please let me know if you still encounter anything.
