### ISSUE TITLE
Eclipse support for Clair

### ISSUE THREAD

**Issue by zborowa** [cwi-swat/clair#3]
I just noticed that Clair requires you to at least use [Eclipse Photon](https://www.eclipse.org/downloads/packages/release/photon/r/eclipse-ide-rcp-and-rap-developers). When used with Mars, Neon or Oxygen (like the Rascal requirements state) you will receive an error during installation of Clair stating a missing `bundle.osgi` or `bundle org.eclipse.cdt.core`. I have also tried to use the newest 2019-03 but that also makes Clair installation fail. Based on this, maybe the documentation (readme) should be updated to reflect this.

**Comment by rodinaarssen** [comment]
Thanks! I added this to the Readme.
