### ISSUE TITLE
Comments field in M3 inaccessable

### ISSUE THREAD

**Issue by bsddemon** [cwi-swat/clair#4]
The following is missing
data M3(list[loc] comments=[]);

**Comment by rodinaarssen** [comment]
Could you clarify where you are missing such a declaration? It is present in [this](https://github.com/cwi-swat/clair/blob/d037c89701a529c07d24655be02e782f2613fe4c/src/lang/cpp/M3.rsc#L21) `M3` declaration.

**Comment by bsddemon** [comment]
If I do the following in my code:
"iprintln(m3.comments);"
I get the message:
"Undeclared field: comments for M3"

Only when I add
"data M3(list[loc] comments=[]);"
I am able to access the comments field. 
This line should not be in my code, but should be fixed in ClaiR

**Comment by rodinaarssen** [comment]
How did you running ClaiR? By downloading the project and importing it into Eclipse, or by installing it through the rascal libraries update site?

**Comment by bsddemon** [comment]
Via Rascal libs site
https://update.rascal-mpl.org/libs/

**Comment by rodinaarssen** [comment]
I checked, and it seemed ClaiR hadn't been updating on that site since last November. I fixed that now, could you try updating and see whether that resolves the issue?

**Comment by bsddemon** [comment]
I updated to the latest and removed the additional line. 
Everything seems to work as before.
Thanks for creating a new release!

**Comment by rodinaarssen** [comment]
Great!
