### ISSUE TITLE
methodInvocations of M3 not filled

### ISSUE THREAD

**Issue by bsddemon** [cwi-swat/clair#8]
If I try the code below, I expect to get a list of method invocation. But it results in an empty list.

`
	m3AndAst = parseCppToM3AndAst(l, includeDirs = includes, additionalMacros = m); 

	M3 m3 = m3AndAst<0>;

	iprint(m3.methodInvocations);
`

**Comment by jurgenvinju** [comment]
I think that's a "not yet implemented", but since all name analysis results are present as loc fields on the ast it requires only a visit of the ast to collect the information and store it, and merging this information from different files.

**Comment by bsddemon** [comment]
What I need is to know in which included header file a function that is called in a cpp file is declared. 
Will methodInvocations help me if it is filled in the described way?

**Comment by rodinaarssen** [comment]
I see what's going on. The `parseCppToM3AndAst` function is a bridge to the Java parser/marshaller. I implemented some of the traversals for M3 in Rascal, which means they are not executed by calling that function. Use `createM3AndAstFromCppFile` instead (same function signature).

You can use the `declarations` table to look up where a function is declared. If you compose the `methodInvocations` relation with the `declarations` relation (the `o` is the compositon operator), you can directly relate function calls to declaration locations, like so: `model.methodInvocations o model.declarations`. (Bear in mind: relation composition is like an Inner Join on database tables).

**Comment by bsddemon** [comment]
Cool! Learned something new; the composition operator :-)

I now have the following code.
`
	m3AndAst = createM3AndAstFromCppFile(l, includeDirs = includes, additionalMacros = m); 
	M3 m3 = m3AndAst<0>;
	iprint(m3.methodInvocations o m3.declarations);
`
